
import enum

class SandboxTestStatus(enum.Enum):
    COLLECT_DEPOSIT_SUCCESS = 1
    COLLECT_DEPOSIT_WEBHOOK_SUCCESS = 1
    COLLECT_VALIDATION_FAIL = 2
    COLLECT_VALIDATION_SUCCESS = 3
    COLLECT_TRANSMISSION_FAIL = 4
    COLLECT_TRANSMISSION_SUCCESS = 5
    COLLECT_STATUSCHECK_FAIL = 6
    COLLECT_STATUSCHECK_PENDING = 7
    COLLECT_STATUSCHECK_SUCCESS = 8
    COLLECT_PAYBACK_FAIL = 9
    COLLECT_PAYBACK_SUCCESS = 10
    DEPOSIT_VALIDATION_FAIL = 11
    DEPOSIT_VALIDATION_SUCCESS = 12
    DEPOSIT_TRANSMISSION_FAIL = 13
    DEPOSIT_TRANSMISSION_PENDING = 14
    DEPOSIT_TRANSMISSION_SUCCESS = 15
    DEPOSIT_STATUSCHECK_FAIL = 16
    DEPOSIT_STATUSCHECK_SUCCESS = 17
    DEPOSIT_PAYBACK_FAIL = 18
    DEPOSIT_PAYBACK_SUCCESS = 19

