




class TibAccountOpenForm:
    def __init__(self, obj=None):
        if obj is None:
            
            self.EnterpriseName = None
            self.EnterpriseAddress = None
            self.EnterpriseCity = None
            self.EnterpriseProvince = None
            self.EnterprisePostalCode = None
            self.EnterprisePhone = None
            self.EnterprisePhone2 = None
            self.EnterpriseEmail = None
            self.EnterpriseAccountResponsible = None
            self.EnterpriseType = None
            self.EnterpriseEstablishedSince = None
            self.EnterpriseTaxeNumber = None
            self.EnterpriseNeq = None
            self.EnterpriseNameAppear = None
            self.BillingName = None
            self.BillingAddress = None
            self.BillingCity = None
            self.BillingProvince = None
            self.BillingPostalCode = None
            self.BillingPhone = None
            self.BillingPhone2 = None
            self.BillingEmail = None
            self.BusinessTypeChoice = None
            self.FirstLeaderName = None
            self.FirstLeaderInitiales = None
            self.FirstLeaderNas = None
            self.FirstLeaderPhone = None
            self.FirstLeaderCellPhone = None
            self.FirstLeaderAddress = None
            self.FirstLeaderProvince = None
            self.FirstLeaderPostalCode = None
            self.FirstLeaderLicenceNumber = None
            self.FirstLeaderBirthDate = None
            self.FirstLeaderSharePart = None
            self.FirstLeaderTitle = None
            self.SecondLeaderName = None
            self.SecondLeaderInitiales = None
            self.SecondLeaderNas = None
            self.SecondLeaderPhone = None
            self.SecondLeaderCellPhone = None
            self.SecondLeaderAddress = None
            self.SecondLeaderProvince = None
            self.SecondLeaderPostalCode = None
            self.SecondLeaderLicenceNumber = None
            self.SecondLeaderBirthDate = None
            self.SecondLeaderSharePart = None
            self.SecondLeaderTitle = None
            self.HadResiliation = None
            self.ResiliationReason = None
            self.HadBankrupted = None
            self.BankruptedReason = None
            self.BeenInVisaRisk = None
            self.VisaRiskReason = None
            self.VisaRiskDate = None
            self.BankName = None
            self.BankAddress = None
            self.BankCity = None
            self.BankProvince = None
            self.BankPostalCode = None
            self.BankPhone = None
            self.BankPhone2 = None
            self.BankEmail = None
            self.SpecimenFile = None
            self.AccountTypeOption = None
            self.BankNumber = None
            self.TransitNumber = None
            self.AccountNumber = None
            self.BeenCompromised = None
            self.PciConformityLevel = None
            self.BeenCompromisedYear = None
            self.UseThirdPartyApplication = None
            self.ThirdPartyApplications = None
            self.ManualCollectionModeCardRatio = None
            self.ManualCollectionModeInternetRatio = None
            self.ManualCollectionModePostalPhoneRatio = None
            self.VolumeCard = None
            self.VolumeAverageTransaction = None
            self.HighestTransaction = None
            self.AlreadyAcceptCard = None
            self.KeepAccount = None
            self.HasRecuringBilling = None
            self.ReasonToChange = None
            self.ServicesAndProductsDescription = None
            self.WantWithdrawDepositService = None
            self.NumberOfTransactionPerMonthWithdraw = None
            self.NumberOfTransactionPerMonthDeposit = None
            self.NumberOfTransactionPerMonthNsf = None
            self.DesiredLimitPerMonthWithdraw = None
            self.DesiredLimitPerMonthDeposit = None
            self.DesiredLimitPerMonthNsf = None
            self.DesireDoubleAuthenticationWithdraw = None
            self.DesireDoubleAuthenticationDeposit = None
            self.DesireDoubleAuthenticationNsf = None
            self.WantCreditCardService = None
            self.CreditCardVolumneMastercard = None
            self.CreditCardVolumneMastercardVisa = None
            self.CreditCardVolumneVisaDebit = None
            self.AcceptVisaDebit = None
            self.AcceptOnlinePayment = None
            self.AcceptTermeCheck = None

        else:
            
            self.EnterpriseName = getattr(obj, 'EnterpriseName', None)
            self.EnterpriseAddress = getattr(obj, 'EnterpriseAddress', None)
            self.EnterpriseCity = getattr(obj, 'EnterpriseCity', None)
            self.EnterpriseProvince = getattr(obj, 'EnterpriseProvince', None)
            self.EnterprisePostalCode = getattr(obj, 'EnterprisePostalCode', None)
            self.EnterprisePhone = getattr(obj, 'EnterprisePhone', None)
            self.EnterprisePhone2 = getattr(obj, 'EnterprisePhone2', None)
            self.EnterpriseEmail = getattr(obj, 'EnterpriseEmail', None)
            self.EnterpriseAccountResponsible = getattr(obj, 'EnterpriseAccountResponsible', None)
            self.EnterpriseType = getattr(obj, 'EnterpriseType', None)
            self.EnterpriseEstablishedSince = getattr(obj, 'EnterpriseEstablishedSince', None)
            self.EnterpriseTaxeNumber = getattr(obj, 'EnterpriseTaxeNumber', None)
            self.EnterpriseNeq = getattr(obj, 'EnterpriseNeq', None)
            self.EnterpriseNameAppear = getattr(obj, 'EnterpriseNameAppear', None)
            self.BillingName = getattr(obj, 'BillingName', None)
            self.BillingAddress = getattr(obj, 'BillingAddress', None)
            self.BillingCity = getattr(obj, 'BillingCity', None)
            self.BillingProvince = getattr(obj, 'BillingProvince', None)
            self.BillingPostalCode = getattr(obj, 'BillingPostalCode', None)
            self.BillingPhone = getattr(obj, 'BillingPhone', None)
            self.BillingPhone2 = getattr(obj, 'BillingPhone2', None)
            self.BillingEmail = getattr(obj, 'BillingEmail', None)
            self.BusinessTypeChoice = getattr(obj, 'BusinessTypeChoice', None)
            self.FirstLeaderName = getattr(obj, 'FirstLeaderName', None)
            self.FirstLeaderInitiales = getattr(obj, 'FirstLeaderInitiales', None)
            self.FirstLeaderNas = getattr(obj, 'FirstLeaderNas', None)
            self.FirstLeaderPhone = getattr(obj, 'FirstLeaderPhone', None)
            self.FirstLeaderCellPhone = getattr(obj, 'FirstLeaderCellPhone', None)
            self.FirstLeaderAddress = getattr(obj, 'FirstLeaderAddress', None)
            self.FirstLeaderProvince = getattr(obj, 'FirstLeaderProvince', None)
            self.FirstLeaderPostalCode = getattr(obj, 'FirstLeaderPostalCode', None)
            self.FirstLeaderLicenceNumber = getattr(obj, 'FirstLeaderLicenceNumber', None)
            self.FirstLeaderBirthDate = getattr(obj, 'FirstLeaderBirthDate', None)
            self.FirstLeaderSharePart = getattr(obj, 'FirstLeaderSharePart', None)
            self.FirstLeaderTitle = getattr(obj, 'FirstLeaderTitle', None)
            self.SecondLeaderName = getattr(obj, 'SecondLeaderName', None)
            self.SecondLeaderInitiales = getattr(obj, 'SecondLeaderInitiales', None)
            self.SecondLeaderNas = getattr(obj, 'SecondLeaderNas', None)
            self.SecondLeaderPhone = getattr(obj, 'SecondLeaderPhone', None)
            self.SecondLeaderCellPhone = getattr(obj, 'SecondLeaderCellPhone', None)
            self.SecondLeaderAddress = getattr(obj, 'SecondLeaderAddress', None)
            self.SecondLeaderProvince = getattr(obj, 'SecondLeaderProvince', None)
            self.SecondLeaderPostalCode = getattr(obj, 'SecondLeaderPostalCode', None)
            self.SecondLeaderLicenceNumber = getattr(obj, 'SecondLeaderLicenceNumber', None)
            self.SecondLeaderBirthDate = getattr(obj, 'SecondLeaderBirthDate', None)
            self.SecondLeaderSharePart = getattr(obj, 'SecondLeaderSharePart', None)
            self.SecondLeaderTitle = getattr(obj, 'SecondLeaderTitle', None)
            self.HadResiliation = getattr(obj, 'HadResiliation', None)
            self.ResiliationReason = getattr(obj, 'ResiliationReason', None)
            self.HadBankrupted = getattr(obj, 'HadBankrupted', None)
            self.BankruptedReason = getattr(obj, 'BankruptedReason', None)
            self.BeenInVisaRisk = getattr(obj, 'BeenInVisaRisk', None)
            self.VisaRiskReason = getattr(obj, 'VisaRiskReason', None)
            self.VisaRiskDate = getattr(obj, 'VisaRiskDate', None)
            self.BankName = getattr(obj, 'BankName', None)
            self.BankAddress = getattr(obj, 'BankAddress', None)
            self.BankCity = getattr(obj, 'BankCity', None)
            self.BankProvince = getattr(obj, 'BankProvince', None)
            self.BankPostalCode = getattr(obj, 'BankPostalCode', None)
            self.BankPhone = getattr(obj, 'BankPhone', None)
            self.BankPhone2 = getattr(obj, 'BankPhone2', None)
            self.BankEmail = getattr(obj, 'BankEmail', None)
            self.SpecimenFile = getattr(obj, 'SpecimenFile', None)
            self.AccountTypeOption = getattr(obj, 'AccountTypeOption', None)
            self.BankNumber = getattr(obj, 'BankNumber', None)
            self.TransitNumber = getattr(obj, 'TransitNumber', None)
            self.AccountNumber = getattr(obj, 'AccountNumber', None)
            self.BeenCompromised = getattr(obj, 'BeenCompromised', None)
            self.PciConformityLevel = getattr(obj, 'PciConformityLevel', None)
            self.BeenCompromisedYear = getattr(obj, 'BeenCompromisedYear', None)
            self.UseThirdPartyApplication = getattr(obj, 'UseThirdPartyApplication', None)
            self.ThirdPartyApplications = getattr(obj, 'ThirdPartyApplications', None)
            self.ManualCollectionModeCardRatio = getattr(obj, 'ManualCollectionModeCardRatio', None)
            self.ManualCollectionModeInternetRatio = getattr(obj, 'ManualCollectionModeInternetRatio', None)
            self.ManualCollectionModePostalPhoneRatio = getattr(obj, 'ManualCollectionModePostalPhoneRatio', None)
            self.VolumeCard = getattr(obj, 'VolumeCard', None)
            self.VolumeAverageTransaction = getattr(obj, 'VolumeAverageTransaction', None)
            self.HighestTransaction = getattr(obj, 'HighestTransaction', None)
            self.AlreadyAcceptCard = getattr(obj, 'AlreadyAcceptCard', None)
            self.KeepAccount = getattr(obj, 'KeepAccount', None)
            self.HasRecuringBilling = getattr(obj, 'HasRecuringBilling', None)
            self.ReasonToChange = getattr(obj, 'ReasonToChange', None)
            self.ServicesAndProductsDescription = getattr(obj, 'ServicesAndProductsDescription', None)
            self.WantWithdrawDepositService = getattr(obj, 'WantWithdrawDepositService', None)
            self.NumberOfTransactionPerMonthWithdraw = getattr(obj, 'NumberOfTransactionPerMonthWithdraw', None)
            self.NumberOfTransactionPerMonthDeposit = getattr(obj, 'NumberOfTransactionPerMonthDeposit', None)
            self.NumberOfTransactionPerMonthNsf = getattr(obj, 'NumberOfTransactionPerMonthNsf', None)
            self.DesiredLimitPerMonthWithdraw = getattr(obj, 'DesiredLimitPerMonthWithdraw', None)
            self.DesiredLimitPerMonthDeposit = getattr(obj, 'DesiredLimitPerMonthDeposit', None)
            self.DesiredLimitPerMonthNsf = getattr(obj, 'DesiredLimitPerMonthNsf', None)
            self.DesireDoubleAuthenticationWithdraw = getattr(obj, 'DesireDoubleAuthenticationWithdraw', None)
            self.DesireDoubleAuthenticationDeposit = getattr(obj, 'DesireDoubleAuthenticationDeposit', None)
            self.DesireDoubleAuthenticationNsf = getattr(obj, 'DesireDoubleAuthenticationNsf', None)
            self.WantCreditCardService = getattr(obj, 'WantCreditCardService', None)
            self.CreditCardVolumneMastercard = getattr(obj, 'CreditCardVolumneMastercard', None)
            self.CreditCardVolumneMastercardVisa = getattr(obj, 'CreditCardVolumneMastercardVisa', None)
            self.CreditCardVolumneVisaDebit = getattr(obj, 'CreditCardVolumneVisaDebit', None)
            self.AcceptVisaDebit = getattr(obj, 'AcceptVisaDebit', None)
            self.AcceptOnlinePayment = getattr(obj, 'AcceptOnlinePayment', None)
            self.AcceptTermeCheck = getattr(obj, 'AcceptTermeCheck', None)


